/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of SDTree.xs. Do not edit this file, edit SDTree.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "lib/Crypt/SDTree.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "sdtree.h"

typedef struct {
	void* object;
} Publisher;


SV* newFromFile(char * class, char * filename) {
	Publisher* publisher;
	SV* obj_ref = newSViv(0);
	SV* obj = newSVrv(obj_ref, class);

	Newx(publisher, 1, Publisher);

	void* object = fpublish_create_from_file(filename);
	publisher->object = object;

	sv_setiv(obj, PTR2IV(publisher));
	SvREADONLY_on(obj);
	return obj_ref;
}

SV* newFromData(char * class, SV* data) {
	Publisher* publisher;
	SV* obj_ref = newSViv(0);
	SV* obj = newSVrv(obj_ref, class);

	New(42, publisher, 1, Publisher);

	/* get string length */
	STRLEN length;
	char* s = SvPV(data, length);
	
	void* object = fpublish_create_from_data(s, length);
	publisher->object = object;

	sv_setiv(obj, PTR2IV(publisher));
	SvREADONLY_on(obj);
	return obj_ref;
}

void printEcInformation(SV* obj) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fpublish_printEcInformation(object);
}

void clearRevokedUsers(SV* obj) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fpublish_clearRevokedUsers(object);
}

void generateCover(SV* obj) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fpublish_generateCover(object);
}

void setRevokelistInverted(SV* obj, unsigned int inverted) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fpublish_setRevokelistInverted(object, inverted);
}

unsigned int getRevokelistInverted(SV* obj) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	unsigned int inverted = fpublish_getRevokelistInverted(object);

	return inverted;
}


void printSDKeyList(SV* obj) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fpublish_printSDKeyList(object);
}

void setTreeSecret(SV* obj, SV* secret) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	
	/* get string length */
	STRLEN length;
	char* data = SvPV(secret, length);
	
	fpublish_setTreeSecret(object, data, length);
}

void DoRevokeUser(SV* obj, char * dpath, int depth) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	tDPath p = StringToDoublePath(dpath);
	if ( depth < 32 ) 
		p |= 0x1LL << ((2* ( 32 - depth) )-1);
	fpublish_revokeuser(object, p);
}

void DoGenerateKeylist(SV* obj, char * path) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	tPath p = StringToPath(path);
	fpublish_generateKeylist(object, p);
}

void writeClientData(SV* obj, char * filename) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fpublish_writeClientData(object, filename);
}

void writeServerData(SV* obj, char * filename) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fpublish_writeServerData(object, filename);
}

SV* getClientData(SV* obj) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fString reply = fpublish_getClientData(object);
	SV* perlreply = newSVpv(reply.data, reply.length);
	free(reply.data);
	
	return perlreply;
}

SV* getServerData(SV* obj) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	fString reply = fpublish_getServerData(object);
	SV* perlreply = newSVpvn(reply.data, reply.length);
	free(reply.data);	

	return perlreply;
}

void publish_DESTROY(SV* obj) {
	Publisher* publisher = (INT2PTR(Publisher*,SvIV(SvRV(obj))));
	fpublish_free(publisher->object);
	Safefree(publisher);
}

SV* generateSDTreeBlock(SV* obj, SV* message) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	
	/* get string length */
	STRLEN length;
	char* data = SvPV(message, length);
	
	fString reply = fpublish_generateSDTreeBlock(object, data, length);
	SV* perlreply = newSVpvn(reply.data, reply.length);
	free(reply.data);	

	return perlreply;
}

SV* generateAESEncryptedBlock(SV* obj, SV* message) {
	void* object = (INT2PTR(Publisher*, SvIV(SvRV(obj))))->object;
	
	/* get string length */
	STRLEN length;
	char* data = SvPV(message, length);
	
	fString reply = fpublish_generateAESEncryptedBlock(object, data, length);
	SV* perlreply = newSVpvn(reply.data, reply.length);
	free(reply.data);	

	return perlreply;
}

typedef struct {
	void* object;
} Subscriber;

SV* subscribe_new(char * class, char * filename) {
	Subscriber* subscriber;
	SV* obj_ref = newSViv(0);
	SV* obj = newSVrv(obj_ref, class);

	New(42, subscriber, 1, Subscriber);

	void* object = fclient_create(filename);
	subscriber->object = object;

	sv_setiv(obj, PTR2IV(subscriber));
	SvREADONLY_on(obj);
	return obj_ref;
}

SV* newFromClientData(char* class, SV* data) {
	Subscriber* subscriber;
	SV* obj_ref = newSViv(0);
	SV* obj = newSVrv(obj_ref, class);

	New(42, subscriber, 1, Subscriber);

	STRLEN length;
	char* s = SvPV(data, length);
	
	void* object = fclient_create_from_data(s, length);
	subscriber->object = object;

	sv_setiv(obj, PTR2IV(subscriber));
	SvREADONLY_on(obj);
	return obj_ref;
}

SV* decrypt(SV* obj, SV* message) {
	void* object = (INT2PTR(Subscriber*, SvIV(SvRV(obj))))->object;
	
	/* get string length */
	STRLEN length;
	char* data = SvPV(message, length);
	
	fString reply = fclient_decrypt(object, data, length);
	SV* perlreply = newSVpvn(reply.data, reply.length);
	free(reply.data);	

	return perlreply;
}

void subscribe_DESTROY(SV* obj) {
	Subscriber* subscriber = (INT2PTR(Subscriber*,SvIV(SvRV(obj))));
	fclient_free(subscriber->object);
	Safefree(subscriber);
}


#line 232 "lib/Crypt/SDTree.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 374 "lib/Crypt/SDTree.c"

XS_EUPXS(XS_Crypt__SDTree_publish_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_publish_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	char *	class = (char *)SvPV_nolen(ST(0))
;
	SV *	RETVAL;

	RETVAL = publish_new(class);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_newFromFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_newFromFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, filename");
    {
	char *	class = (char *)SvPV_nolen(ST(0))
;
	char *	filename = (char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;

	RETVAL = newFromFile(class, filename);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_newFromData); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_newFromData)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, data");
    {
	char *	class = (char *)SvPV_nolen(ST(0))
;
	SV *	data = ST(1)
;
	SV *	RETVAL;

	RETVAL = newFromData(class, data);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_printEcInformation); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_printEcInformation)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
#line 245 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 450 "lib/Crypt/SDTree.c"
#line 247 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	printEcInformation(obj);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 461 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_clearRevokedUsers); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_clearRevokedUsers)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
#line 261 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 481 "lib/Crypt/SDTree.c"
#line 263 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	clearRevokedUsers(obj);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 492 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_generateCover); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_generateCover)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
#line 277 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 512 "lib/Crypt/SDTree.c"
#line 279 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	generateCover(obj);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 523 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_setRevokelistInverted); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_setRevokelistInverted)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, inverted");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
	unsigned int	inverted = (unsigned int)SvUV(ST(1))
;
#line 294 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 545 "lib/Crypt/SDTree.c"
#line 296 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	setRevokelistInverted(obj, inverted);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 556 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_getRevokelistInverted); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_getRevokelistInverted)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    {
	SV *	obj = ST(0)
;
	unsigned int	RETVAL;
	dXSTARG;

	RETVAL = getRevokelistInverted(obj);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_printSDKeyList); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_printSDKeyList)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
#line 314 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 595 "lib/Crypt/SDTree.c"
#line 316 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	printSDKeyList(obj);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 606 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_setTreeSecret); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_setTreeSecret)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, secret");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
	SV *	secret = ST(1)
;
#line 331 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 628 "lib/Crypt/SDTree.c"
#line 333 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	setTreeSecret(obj, secret);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 639 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_DoRevokeUser); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_DoRevokeUser)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "obj, dpath, depth");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
	char *	dpath = (char *)SvPV_nolen(ST(1))
;
	int	depth = (int)SvIV(ST(2))
;
#line 349 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 663 "lib/Crypt/SDTree.c"
#line 351 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	DoRevokeUser(obj, dpath, depth);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 674 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_DoGenerateKeylist); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_DoGenerateKeylist)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 366 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 696 "lib/Crypt/SDTree.c"
#line 368 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	DoGenerateKeylist(obj, path);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 707 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_writeClientData); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_writeClientData)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, filename");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
	char *	filename = (char *)SvPV_nolen(ST(1))
;
#line 383 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 729 "lib/Crypt/SDTree.c"
#line 385 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	writeClientData(obj, filename);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 740 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_writeServerData); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_writeServerData)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, filename");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
	char *	filename = (char *)SvPV_nolen(ST(1))
;
#line 400 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 762 "lib/Crypt/SDTree.c"
#line 402 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	writeServerData(obj, filename);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 773 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_getClientData); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_getClientData)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    {
	SV *	obj = ST(0)
;
	SV *	RETVAL;

	RETVAL = getClientData(obj);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_getServerData); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_getServerData)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    {
	SV *	obj = ST(0)
;
	SV *	RETVAL;

	RETVAL = getServerData(obj);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_publish_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_publish_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
#line 424 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 831 "lib/Crypt/SDTree.c"
#line 426 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	publish_DESTROY(obj);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 842 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Crypt__SDTree_generateSDTreeBlock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_generateSDTreeBlock)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, message");
    {
	SV *	obj = ST(0)
;
	SV *	message = ST(1)
;
	SV *	RETVAL;

	RETVAL = generateSDTreeBlock(obj, message);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_generateAESEncryptedBlock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_generateAESEncryptedBlock)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, message");
    {
	SV *	obj = ST(0)
;
	SV *	message = ST(1)
;
	SV *	RETVAL;

	RETVAL = generateAESEncryptedBlock(obj, message);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_subscribe_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_subscribe_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, filename");
    {
	char *	class = (char *)SvPV_nolen(ST(0))
;
	char *	filename = (char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;

	RETVAL = subscribe_new(class, filename);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_newFromClientData); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_newFromClientData)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, data");
    {
	char *	class = (char *)SvPV_nolen(ST(0))
;
	SV *	data = ST(1)
;
	SV *	RETVAL;

	RETVAL = newFromClientData(class, data);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_decrypt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_decrypt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "obj, message");
    {
	SV *	obj = ST(0)
;
	SV *	message = ST(1)
;
	SV *	RETVAL;

	RETVAL = decrypt(obj, message);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Crypt__SDTree_subscribe_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Crypt__SDTree_subscribe_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	obj = ST(0)
;
#line 465 "lib/Crypt/SDTree.xs"
	I32* temp;
#line 967 "lib/Crypt/SDTree.c"
#line 467 "lib/Crypt/SDTree.xs"
	temp = PL_markstack_ptr++;
	subscribe_DESTROY(obj);
	if (PL_markstack_ptr != temp) {
          /* truly void, because dXSARGS not invoked */
	  PL_markstack_ptr = temp;
	  XSRETURN_EMPTY; /* return empty stack */
        }
        /* must have used dXSARGS; list context implied */
	return; /* assume stack size is correct */
#line 978 "lib/Crypt/SDTree.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Crypt__SDTree); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Crypt__SDTree)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Crypt::SDTree::publish_new", XS_Crypt__SDTree_publish_new, file);
        newXS("Crypt::SDTree::newFromFile", XS_Crypt__SDTree_newFromFile, file);
        newXS("Crypt::SDTree::newFromData", XS_Crypt__SDTree_newFromData, file);
        newXS("Crypt::SDTree::printEcInformation", XS_Crypt__SDTree_printEcInformation, file);
        newXS("Crypt::SDTree::clearRevokedUsers", XS_Crypt__SDTree_clearRevokedUsers, file);
        newXS("Crypt::SDTree::generateCover", XS_Crypt__SDTree_generateCover, file);
        newXS("Crypt::SDTree::setRevokelistInverted", XS_Crypt__SDTree_setRevokelistInverted, file);
        newXS("Crypt::SDTree::getRevokelistInverted", XS_Crypt__SDTree_getRevokelistInverted, file);
        newXS("Crypt::SDTree::printSDKeyList", XS_Crypt__SDTree_printSDKeyList, file);
        newXS("Crypt::SDTree::setTreeSecret", XS_Crypt__SDTree_setTreeSecret, file);
        newXS("Crypt::SDTree::DoRevokeUser", XS_Crypt__SDTree_DoRevokeUser, file);
        newXS("Crypt::SDTree::DoGenerateKeylist", XS_Crypt__SDTree_DoGenerateKeylist, file);
        newXS("Crypt::SDTree::writeClientData", XS_Crypt__SDTree_writeClientData, file);
        newXS("Crypt::SDTree::writeServerData", XS_Crypt__SDTree_writeServerData, file);
        newXS("Crypt::SDTree::getClientData", XS_Crypt__SDTree_getClientData, file);
        newXS("Crypt::SDTree::getServerData", XS_Crypt__SDTree_getServerData, file);
        newXS("Crypt::SDTree::publish_DESTROY", XS_Crypt__SDTree_publish_DESTROY, file);
        newXS("Crypt::SDTree::generateSDTreeBlock", XS_Crypt__SDTree_generateSDTreeBlock, file);
        newXS("Crypt::SDTree::generateAESEncryptedBlock", XS_Crypt__SDTree_generateAESEncryptedBlock, file);
        newXS("Crypt::SDTree::subscribe_new", XS_Crypt__SDTree_subscribe_new, file);
        newXS("Crypt::SDTree::newFromClientData", XS_Crypt__SDTree_newFromClientData, file);
        newXS("Crypt::SDTree::decrypt", XS_Crypt__SDTree_decrypt, file);
        newXS("Crypt::SDTree::subscribe_DESTROY", XS_Crypt__SDTree_subscribe_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

